name: API Tests

on:
  push:
    branches: [ main, master ]  # Added master for repositories using master as default
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Added timeout for safety

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 (latest stable)
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Updated to v4 (latest stable)
      with:
        java-version: '11'
        distribution: 'temurin'  # Changed to Temurin (formerly AdoptOpenJDK)
        cache: 'maven'  # Enables built-in Maven caching
    
    - name: Cache Maven packages
      uses: actions/cache@v4  # Updated to v4 (latest stable)
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    
    - name: Run tests
      run: mvn -B clean test  # Added -B for batch mode
    
    - name: Upload test results
      if: always()  # Runs even if previous steps fail
      uses: actions/upload-artifact@v4  # Updated to v4 (latest stable)
      with:
        name: test-results
        path: |
          target/surefire-reports/*
          target/failsafe-reports/*
        retention-days: 7  # Keep artifacts for 7 days
    
    - name: Report Status
      if: always()
      uses: actions/github-script@v7  # Added for status reporting
      with:
        script: |
          const workflow = await github.rest.actions.getWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const conclusion = workflow.data.conclusion;
          
          if (conclusion === 'success') {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '✅ All tests passed successfully!'
            });
          } else if (conclusion === 'failure') {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ Some tests failed. Please check the test results.'
            });
          }